version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    restart: unless-stopped

  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      NEO4J_USER: neo4j
      NEO4J_PASS: password
      NEO4J_HOST: neo4j

    depends_on:
      - neo4j

    volumes:
      - .:/app

